### PR TITLE
Big language step forward

### PR DESCRIPTION
**Pull request by DanySK**
This pull request introduces many new features and solves a critical bug.

Rationale: solution to critical bug Protelis/Protelis#249 required to entirely restructure parser and validator. I took the opportunity to improve several aspects that were perceived as critical, e.g. dealing with semicolon, improving error reporting, and getting closer with syntax to modern JVM languages.

* Fixes Protelis/Protelis#249
* Introduces Kotlin/Scala style invocation, no need of `.apply`, this is now a valid program:
```
def f(a) { a }
a(1)
```
* Introduces Kotlin-style lambda. Former Java-style lambda are still supported, except for out of parenthesis.
```
myhof(0, (a, b) -> { a + b }) // Old style
myhof(0. { a, b -> a + b }) // New style
myhof(0) { a, b ->
   a + b
} // New style, with out-of-parenthesis last lambda
```
* Introduces Kotlin-style short lambda and Kotlin/Xtend style `it` variable
```
inc(0, i -> i + 1) // Old style
inc(0, { i -> i + 1}) // Kt style
inc(0) { i -> i + 1} // Kt style, out-of-parenthesis last lambda
inc(0, { it + 1}) // Kt style with it
inc(0) { it + 1} // Kt style, it + out-of-parenthesis
```
* Semicolon are now dealt with Kotlin style. They are no longer needed, except for disambiguation, e.g.:
```
myVar { it + 1 } // Invokes myVar passing a lambda as only parameter
myVar; { it + 1} // Evaluates myVar, then evaluates and returns a lambda that increments by 1
```
We should actually raise warnings for expressions that do not return nor can cause side effects (e.g. the program `1 1`, now valid, should raise warnings.
* Deprecate variable re-assignment
* Deprecate old (java) style lambda expressions. A warning with a prompt on how to convert is raised.

### CODE REVIEW

**Comment by DanySK** [comment]
To make it work, very small. The only change that is not retrocompatible is the `it` keyword, so if some variable is named `it` it will throw errors. The impact should be much less relevant than a few recent changes, such as the drop of `pi`, `e`, and `Infinity` from the keyword set.

Removing all the warnings it's a different job. The new validator complains a lot more than the old one. Moreover, a lot of them will be generated by the new hoods.

Two more points:

* I forgot to mention that it is now possible to access java packages / classes / methods whose name is `share`, `module`, `rep`, `nbr`, and so on.

* I'd like to propose a further addition, which is a simplified `if` and `mux`, to be used in a way similar to the Java ternary operator. Similar syntax is available in Kotlin / Scala / Xtend and so on: `if (condition) singleExpression else otherExpression`. No parentheses. No multiple expressions or side effects allowed. Not available for "if without else". This kind of `if` is a bad code practice in Java because if does not yield a value (the ternary operator does the job), but languages more similar to Protelis allow this syntax.

**Comment by jakebeal** [comment]
OK, let's have the pull request set up, and then I'll review it and approve both.

As for the ternary operator: let's open that as a future issue to consider.

**Comment by DanySK** [comment]
@jakebeal application of the new parser rules on existing protelis-lang from develop results in:
* no errors
* 171 warnings (most due to usage of old hoods, some due to usage of "old" lambda format, some due to usage of `.apply()` rather than direct `()` application)
* 214 information messages (unnecessary imports and single-expression methods)

I no point there was an usage of `it` as variable, so in the case of protelis-lang this update does not introduce any non-backward compatible change.

**Comment by jakebeal** [comment]
Great: given these results validating backward compatibility, I approve.

**Pull request merged**
